apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  labels:
    app: web-app-dep
  namespace: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: webapp
        image: avasthi20/flask-test:17
        ports:
        - containerPort: 5000

